package com.chestautosorter.gametest;

import com.chestautosorter.core.Category;
import com.chestautosorter.core.ItemClassifier;
import com.chestautosorter.core.McStackKey;
import com.chestautosorter.server.ChestSnapshot;
import com.chestautosorter.server.SafeCommitter;
import com.chestautosorter.server.SortPipelines;
import com.chestautosorter.server.SupportedChests;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.component.DataComponents;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;
import net.minecraft.world.Container;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.ChestBlock;
import net.minecraft.world.level.block.state.properties.ChestType;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Real-world gametests: build vanilla chests in the test structure and drive the *production*
 * pipeline (snapshot -> classify -> plan -> {@link SafeCommitter#commit}). Expectations are written
 * out explicitly here, never derived from the code under test.
 */
public final class SortGameTests {

    private SortGameTests() {}

    // --- container helpers -------------------------------------------------------------------

    /** Minimal production-equivalent view: read a slot, write a slot, know the slot count. */
    static List<Container> containersOf(GameTestHelper helper, BlockPos... positions) {
        List<Container> out = new ArrayList<>();
        for (BlockPos p : positions) {
            Container c = SupportedChests.resolve(helper.getLevel(), helper.absolutePos(p));
            if (c == null) {
                throw new IllegalStateException("unresolved container at " + p);
            }
            out.add(c);
        }
        return out;
    }

    static void fill(Container c, int slot, ItemStack stack) {
        c.setItem(slot, stack);
    }

    // --- tests --------------------------------------------------------------------------------

    /**
     * Three single chests, each pre-mixed with wood / stone / ore, are redistributed across boxes by
     * category. Asserts cross-chest movement, per-slot counts, full component data, and that a fourth
     * (non-participating) chest is untouched.
     */
    public static void mixedChestsAreRedistributedByCategory(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        BlockPos c = new BlockPos(5, 1, 1);
        BlockPos bystander = new BlockPos(7, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        helper.setBlock(c, Blocks.CHEST);
        helper.setBlock(bystander, Blocks.CHEST);

        List<Container> boxes = containersOf(helper, a, b, c);
        Container ca = boxes.get(0);
        Container cb = boxes.get(1);
        Container cc = boxes.get(2);
        Container cbystander = containersOf(helper, bystander).get(0);

        // Deliberately wrong boxes: every chest holds a mix of all three categories.
        // WOOD
        fill(ca, 0, new ItemStack(Items.OAK_LOG, 30));
        fill(cb, 0, new ItemStack(Items.OAK_PLANKS, 12));
        fill(cc, 0, new ItemStack(Items.OAK_LOG, 10));
        // STONE
        fill(ca, 1, new ItemStack(Items.STONE, 40));
        fill(cb, 1, new ItemStack(Items.COBBLESTONE, 20));
        fill(cc, 1, new ItemStack(Items.STONE, 5));
        // ORE
        fill(ca, 2, new ItemStack(Items.IRON_INGOT, 25));
        fill(cb, 2, new ItemStack(Items.GOLD_INGOT, 15));
        fill(cc, 2, new ItemStack(Items.DIAMOND, 3));

        // The bystander must never be touched.
        fill(cbystander, 0, new ItemStack(Items.APPLE, 9));

        ItemStack bystanderBefore = cbystander.getItem(0).copy();

        List<Container> participating = List.of(ca, cb, cc);
        Map<String, Long> before = tally(participating);
        // Explicit expectations (not generated by the code under test).
        assertEquals(helper, 40L, before.get("minecraft:oak_log"), "oak_log before");
        assertEquals(helper, 12L, before.get("minecraft:oak_planks"), "oak_planks before");
        assertEquals(helper, 45L, before.get("minecraft:stone"), "stone before");
        assertEquals(helper, 20L, before.get("minecraft:cobblestone"), "cobblestone before");
        assertEquals(helper, 25L, before.get("minecraft:iron_ingot"), "iron before");
        assertEquals(helper, 15L, before.get("minecraft:gold_ingot"), "gold before");
        assertEquals(helper, 3L, before.get("minecraft:diamond"), "diamond before");

        List<ChestSnapshot> snaps = new ArrayList<>();
        snaps.add(ChestSnapshot.of(helper.absolutePos(a), ca, false));
        snaps.add(ChestSnapshot.of(helper.absolutePos(b), cb, false));
        snaps.add(ChestSnapshot.of(helper.absolutePos(c), cc, false));

        // --- run the PRODUCTION pipeline ---
        SortPipelines.Outcome outcome = SortPipelines.runProduction(participating, snaps, true);
        if (!outcome.success) {
            helper.fail("pipeline failed: " + outcome.message);
            return;
        }

        // --- 1. conservation on real containers, per identity ---
        Map<String, Long> after = tally(participating);
        if (!before.equals(after)) {
            helper.fail("conservation broken: before=" + before + " after=" + after);
            return;
        }

        // --- 2. the layout really is category-dedicated and cross-chest ---
        for (int i = 0; i < participating.size(); i++) {
            Category expected = switch (i) {
                case 0 -> Category.WOOD;
                case 1 -> Category.STONE_BUILDING;
                default -> Category.ORE;
            };
            Category actual = dominantCategory(participating.get(i));
            if (actual != null && actual != expected) {
                helper.fail("box" + i + " holds " + actual + " but expected " + expected);
                return;
            }
        }

        // Box 0 originally mixed all three categories and must no longer do so.
        if (distinctCategories(ca) >= 3) {
            StringBuilder cls = new StringBuilder();
            for (int i = 0; i < ca.getContainerSize(); i++) {
                ItemStack s = ca.getItem(i);
                if (!s.isEmpty()) {
                    cls.append(id(s)).append('=')
                            .append(catOf(s)).append(' ');
                }
            }
            helper.fail("box0 still mixes all three categories; no cross-chest redistribution happened"
                    + " | box0=" + dump(ca) + " box1=" + dump(cb) + " box2=" + dump(cc)
                    + " | status=" + outcome.plan.status + " msgs=" + outcome.plan.messages
                    + " | classified: " + cls);
            return;
        }
        // Cross-chest proof: ores started spread over boxes 0/1/2; after a dedicated layout every ore
        // must sit in a single box, so at least two of the three original boxes lost their ore.
        int oreBoxes = 0;
        for (Container box : participating) {
            if (containerHasItem(box, Items.IRON_INGOT) || containerHasItem(box, Items.GOLD_INGOT)
                    || containerHasItem(box, Items.DIAMOND)) {
                oreBoxes++;
            }
        }
        if (oreBoxes != 1) {
            helper.fail("expected all ores consolidated into exactly 1 box, found " + oreBoxes);
            return;
        }

        // --- 4. bystander untouched ---
        ItemStack bystanderAfter = cbystander.getItem(0);
        if (!ItemStack.matches(bystanderBefore, bystanderAfter)) {
            helper.fail("non-participating chest was modified");
            return;
        }

        helper.succeed();
    }

    /** A properly-formed double chest must resolve as one 54-slot logical container. */
    public static void doubleChestIsOneContainer(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        // Two chests only merge when their TYPE states point at each other, which vanilla normally
        // establishes through updateShape when a player places the second half. setBlock bypasses
        // that, so the states must be written explicitly.
        // With FACING=NORTH, getConnectedDirection is EAST for LEFT and WEST for RIGHT, so the LEFT
        // half must sit at the lower x and the RIGHT half at the higher x.
        helper.setBlock(a, Blocks.CHEST.defaultBlockState()
                .setValue(ChestBlock.FACING, Direction.NORTH)
                .setValue(ChestBlock.TYPE, ChestType.LEFT));
        helper.setBlock(new BlockPos(2, 1, 1), Blocks.CHEST.defaultBlockState()
                .setValue(ChestBlock.FACING, Direction.NORTH)
                .setValue(ChestBlock.TYPE, ChestType.RIGHT));

        Container whole = SupportedChests.resolve(helper.getLevel(), helper.absolutePos(a));
        if (whole == null || whole.getContainerSize() != 54) {
            helper.fail("double chest size wrong: " + (whole == null ? "null" : whole.getContainerSize()));
            return;
        }
        for (int i = 0; i < 54; i++) {
            whole.setItem(i, new ItemStack(Items.COBBLESTONE, 64));
        }
        whole.setChanged();
        if (count(whole, Items.COBBLESTONE) != 54L * 64L) {
            helper.fail("double chest contents wrong");
            return;
        }
        helper.succeed();
    }

    /** After a successful commit, item identities and counts are conserved, including components. */
    public static void commitConservesComponents(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        Container ca = SupportedChests.resolve(helper.getLevel(), helper.absolutePos(a));
        if (ca == null) {
            helper.fail("no container");
            return;
        }
        ItemStack named = new ItemStack(Items.DIAMOND_SWORD);
        named.set(DataComponents.CUSTOM_NAME, Component.literal("Test Sword"));
        ca.setItem(0, named);
        ca.setItem(1, new ItemStack(Items.DIAMOND_SWORD));
        ca.setItem(2, new ItemStack(Items.OAK_LOG, 64));
        ca.setChanged();

        List<Container> containers = List.of(ca);
        List<ChestSnapshot> snaps = List.of(ChestSnapshot.of(helper.absolutePos(a), ca, false));
        SortPipelines.Outcome outcome = SortPipelines.runProduction(containers, snaps, true);
        if (!outcome.success) {
            helper.fail("pipeline failed: " + outcome.message);
            return;
        }
        boolean hasNamed = false;
        boolean hasPlain = false;
        for (int i = 0; i < ca.getContainerSize(); i++) {
            ItemStack s = ca.getItem(i);
            if (!s.isEmpty() && s.is(Items.DIAMOND_SWORD)) {
                if (s.get(DataComponents.CUSTOM_NAME) != null) {
                    hasNamed = true;
                } else {
                    hasPlain = true;
                }
            }
        }
        if (!hasNamed || !hasPlain) {
            helper.fail("component identity lost: named=" + hasNamed + " plain=" + hasPlain);
            return;
        }
        helper.succeed();
    }

    /**
     * B: the inventory changes between snapshot and write. The commit must refuse and must NOT write,
     * and in particular must not clobber the fresh change with the stale snapshot.
     */
    public static void commitRejectsWhenInventoryChanged(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        Container ca = SupportedChests.resolve(helper.getLevel(), helper.absolutePos(a));
        if (ca == null) {
            helper.fail("no container");
            return;
        }
        ca.setItem(0, new ItemStack(Items.OAK_LOG, 10));
        ca.setItem(1, new ItemStack(Items.IRON_INGOT, 10));
        ca.setChanged();

        List<Container> containers = List.of(ca);
        List<ChestSnapshot> snaps = List.of(ChestSnapshot.of(helper.absolutePos(a), ca, false));
        SafeCommitter.Prepared prepared = SafeCommitter.prepare(containers, List.of(key(helper, a)));

        // Simulate another actor changing the chest AFTER the snapshot was taken.
        ItemStack intruder = new ItemStack(Items.DIAMOND, 7);
        ca.setItem(0, intruder);

        List<com.chestautosorter.core.StackEntry> entries = SortPipelines.entries(snaps, containers);
        var plan = com.chestautosorter.core.SortPlanner.plan(List.of(snaps.get(0).size),
                com.chestautosorter.core.StackAggregator.aggregate(entries), true);
        if (plan.isCancelled()) {
            helper.fail("unexpected planner cancellation");
            return;
        }
        SafeCommitter.Outcome outcome = SafeCommitter.commit(prepared, plan.layout);

        if (outcome.success) {
            helper.fail("commit succeeded despite inventory change");
            return;
        }
        // The fresh change must survive untouched; the stale snapshot must NOT be restored over it.
        if (!ItemStack.matches(intruder, ca.getItem(0))) {
            helper.fail("stale snapshot was restored over the new change: " + ca.getItem(0));
            return;
        }
        if (!ca.getItem(1).is(Items.IRON_INGOT) || ca.getItem(1).getCount() != 10) {
            helper.fail("slot1 was modified: " + ca.getItem(1));
            return;
        }
        helper.succeed();
    }

    /**
     * D: a write fails partway through. The already-modified slots must be restored to the exact
     * pre-commit state (verified by reading the real containers), not merely reported as rolled back.
     */
    public static void commitRollsBackOnPartialWriteFailure(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        List<Container> containers = containersOf(helper, a, b);
        Container ca = containers.get(0);
        Container cb = containers.get(1);

        ca.setItem(0, new ItemStack(Items.OAK_LOG, 30));
        ca.setItem(1, new ItemStack(Items.STONE, 20));
        cb.setItem(0, new ItemStack(Items.IRON_INGOT, 15));
        cb.setItem(1, new ItemStack(Items.GOLD_INGOT, 5));
        ca.setChanged();
        cb.setChanged();

        List<ChestSnapshot> snaps = List.of(
                ChestSnapshot.of(helper.absolutePos(a), ca, false),
                ChestSnapshot.of(helper.absolutePos(b), cb, false));
        List<com.chestautosorter.core.StackEntry> entries = SortPipelines.entries(snaps, containers);
        // The committer materializes stacks from prototypes keyed by identity, exactly as the
        // production pipeline does; this test drives commit() directly, so seed them here.
        com.chestautosorter.server.PlannedStacks.begin();
        var plan = com.chestautosorter.core.SortPlanner.plan(
                List.of(snaps.get(0).size, snaps.get(1).size),
                com.chestautosorter.core.StackAggregator.aggregate(entries), true);
        if (plan.isCancelled()) {
            com.chestautosorter.server.PlannedStacks.end();
            helper.fail("unexpected planner cancellation");
            return;
        }
        for (ChestSnapshot snap : snaps) {
            for (int i = 0; i < snap.size; i++) {
                ItemStack s = snap.slots.get(i);
                if (!s.isEmpty()) {
                    com.chestautosorter.server.PlannedStacks.put(com.chestautosorter.core.McStackKey.of(s), s);
                }
            }
        }

        SafeCommitter.Prepared prepared = SafeCommitter.prepare(containers, List.of(key(helper, a), key(helper, b)));
        // Snapshot the true pre-commit state, read from the real containers.
        List<ItemStack> expectedA = slots(ca);
        List<ItemStack> expectedB = slots(cb);

        // Inject a failure only AFTER at least one slot has been overwritten with content that
        // differs from the original. Failing earlier would leave the containers untouched, and the
        // slot-by-slot comparison below would then pass even if rollback were a no-op.
        // The hook runs before the write, so divergence is detected by asking the committer which
        // stack it is about to place, and comparing that against the original slot contents.
        final boolean[] diverged = {false};
        final int[] writes = {0};
        SafeCommitter.setHooks(new SafeCommitter.Hooks() {
            @Override
            public void beforeWrite(Container container, int slot, ItemStack incoming) {
                int idx = container == ca ? slot : (container == cb ? slot : -1);
                List<ItemStack> orig = container == ca ? expectedA : expectedB;
                if (idx >= 0 && idx < orig.size()) {
                    if (diverged[0]) {
                        throw new RuntimeException("injected write failure after real divergence");
                    }
                    if (!ItemStack.matches(incoming, orig.get(idx))) {
                        diverged[0] = true;
                    }
                }
                writes[0]++;
            }
        });
        SafeCommitter.Outcome outcome;
        try {
            outcome = SafeCommitter.commit(prepared, plan.layout);
        } finally {
            SafeCommitter.clearHooks();
            com.chestautosorter.server.PlannedStacks.end();
        }

        // Guard against a vacuous test: the injection must have fired on a genuinely changed slot.
        if (!diverged[0]) {
            helper.fail("test setup is vacuous: no slot was overwritten with different content before"
                    + " the injected failure (" + writes[0] + " writes); plan=" + planDesc(plan)
                    + " expectedA=" + dumpList(expectedA) + " expectedB=" + dumpList(expectedB));
            return;
        }
        if (outcome.success) {
            helper.fail("commit reported success despite injected failure");
            return;
        }
        if (!outcome.rolledBack) {
            helper.fail("commit did not roll back");
            return;
        }
        if (!outcome.rollbackVerified) {
            helper.fail("rollback verification failed");
            return;
        }
        // Read the REAL containers and compare slot-by-slot, including full item data.
        assertSlotsEqual(helper, expectedA, slots(ca), "chest A after rollback");
        assertSlotsEqual(helper, expectedB, slots(cb), "chest B after rollback");
        helper.succeed();
    }

    // --- assertion helpers --------------------------------------------------------------------

    /**
     * C: when mixed packing is disallowed and categories cannot each own a chest, the whole sort is
     * cancelled and every slot of the real containers is left byte-for-byte identical.
     */
    public static void mixedDisallowedCancelsAndLeavesChestsUntouched(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        List<Container> containers = containersOf(helper, a, b);
        Container ca = containers.get(0);
        Container cb = containers.get(1);

        // Three categories spread over two chests: dedicated layout is impossible.
        ca.setItem(0, new ItemStack(Items.OAK_LOG, 10));
        ca.setItem(1, new ItemStack(Items.STONE, 10));
        cb.setItem(0, new ItemStack(Items.IRON_INGOT, 10));
        cb.setItem(1, new ItemStack(Items.DIAMOND_SWORD, 1));
        ca.setChanged();
        cb.setChanged();

        List<ItemStack> beforeA = slots(ca);
        List<ItemStack> beforeB = slots(cb);

        List<ChestSnapshot> snaps = List.of(
                ChestSnapshot.of(helper.absolutePos(a), ca, false),
                ChestSnapshot.of(helper.absolutePos(b), cb, false));

        // allowMixed = false must cancel rather than fall back to mixed packing.
        SortPipelines.Plan plan = SortPipelines.plan(containers, snaps, false);
        if (!plan.isCancelled()) {
            helper.fail("expected cancellation with allowMixed=false, got " + plan.planner.status);
            return;
        }
        // Nothing may have been written by planning alone.
        assertSlotsEqual(helper, beforeA, slots(ca), "chest A after cancelled plan");
        assertSlotsEqual(helper, beforeB, slots(cb), "chest B after cancelled plan");

        // The same inventory with mixed allowed and capacity available must succeed.
        SortPipelines.Plan ok = SortPipelines.plan(containers, snaps, true);
        if (ok.isCancelled()) {
            helper.fail("mixed layout should fit but was cancelled: " + ok.messages());
            return;
        }
        helper.succeed();
    }

    /**
     * D2: the read-back after writing disagrees because a stacked count was silently truncated.
     * The committer must detect this, roll back, and the real containers must equal the original.
     * Distinct from the thrown-exception case: nothing here throws during writing.
     */
    public static void commitRollsBackOnReadbackMismatch(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        List<Container> containers = containersOf(helper, a, b);
        Container ca = containers.get(0);
        Container cb = containers.get(1);

        // Items deliberately in the "wrong" chests so the committed layout must move them.
        ca.setItem(0, new ItemStack(Items.IRON_INGOT, 20));
        ca.setItem(1, new ItemStack(Items.OAK_LOG, 40));
        cb.setItem(0, new ItemStack(Items.STONE, 25));
        ca.setChanged();
        cb.setChanged();

        List<ChestSnapshot> snaps = List.of(
                ChestSnapshot.of(helper.absolutePos(a), ca, false),
                ChestSnapshot.of(helper.absolutePos(b), cb, false));
        SortPipelines.Plan plan = SortPipelines.plan(containers, snaps, true);
        if (plan.isCancelled()) {
            helper.fail("unexpected cancellation");
            return;
        }

        // Find a slot the plan actually rewrites with different content; tampering anywhere else
        // would leave the read-back matching the plan and prove nothing.
        com.chestautosorter.server.PlannedStacks.begin();
        SafeCommitter.BlockPosKey[] target = {null};
        int targetSlot = -1;
        boolean found = false;
        try {
            for (ChestSnapshot snap : snaps) {
                for (int i = 0; i < snap.size; i++) {
                    ItemStack s = snap.slots.get(i);
                    if (!s.isEmpty()) {
                        com.chestautosorter.server.PlannedStacks.put(com.chestautosorter.core.McStackKey.of(s), s);
                    }
                }
            }
            for (com.chestautosorter.core.SortPlanner.SlotPlan p : plan.planner.layout) {
                if (p.isEmpty()) {
                    continue;
                }
                Container c = containers.get(p.container);
                ItemStack orig = c.getItem(p.slot);
                ItemStack planned = com.chestautosorter.server.PlannedStacks.materialize(p.entry);
                if (!ItemStack.matches(orig, planned)) {
                    target[0] = p.container == 0 ? key(helper, a) : key(helper, b);
                    targetSlot = p.slot;
                    found = true;
                    break;
                }
            }
        } finally {
            com.chestautosorter.server.PlannedStacks.end();
        }
        if (!found) {
            helper.fail("test setup is vacuous: the plan rewrites no slot with different content");
            return;
        }
        final boolean[] swapped = {false};
        final String[] swapInfo = {""};
        List<ItemStack> expectedA = slots(ca);
        List<ItemStack> expectedB = slots(cb);

        // Tamper AFTER writing, BEFORE verification. The tamper must preserve global totals (so the
        // conservation check cannot catch it) while breaking the slot layout, so that only the
        // layout read-back can detect it. Swapping two filled slots achieves exactly that.
        SafeCommitter.setHooks(new SafeCommitter.Hooks() {
            @Override
            public void afterWrites() {
                try {
                    for (Container c : containers) {
                        List<Integer> filled = new ArrayList<>();
                        for (int i = 0; i < c.getContainerSize(); i++) {
                            if (!c.getItem(i).isEmpty()) {
                                filled.add(i);
                            }
                        }
                        if (filled.size() >= 2) {
                            int i0 = filled.get(0);
                            int i1 = filled.get(1);
                            ItemStack a0 = c.getItem(i0).copy();
                            ItemStack a1 = c.getItem(i1).copy();
                            c.setItem(i0, a1);
                            c.setItem(i1, a0);
                            swapped[0] = true;
                            swapInfo[0] = "swapped slots " + i0 + " and " + i1;
                            return;
                        }
                    }
                    swapInfo[0] = "no container had two filled slots: A=" + dump(ca) + " B=" + dump(cb);
                } catch (Throwable t) {
                    swapInfo[0] = "tamper threw: " + t;
                }
            }
        });
        SafeCommitter.Prepared prepared = SafeCommitter.prepare(containers, List.of(key(helper, a), key(helper, b)));
        com.chestautosorter.server.PlannedStacks.begin();
        SafeCommitter.Outcome outcome;
        try {
            for (ChestSnapshot snap : snaps) {
                for (int i = 0; i < snap.size; i++) {
                    ItemStack s = snap.slots.get(i);
                    if (!s.isEmpty()) {
                        com.chestautosorter.server.PlannedStacks.put(com.chestautosorter.core.McStackKey.of(s), s);
                    }
                }
            }
            outcome = SafeCommitter.commit(prepared, plan.planner.layout);
        } finally {
            SafeCommitter.clearHooks();
            com.chestautosorter.server.PlannedStacks.end();
        }

        if (!swapped[0]) {
            helper.fail("test setup is vacuous: could not swap two filled slots. " + swapInfo[0]);
            return;
        }
        if (outcome.success) {
            helper.fail("commit reported success despite a read-back layout mismatch"
                    + " (totals unchanged, so only the layout check can catch this)");
            return;
        }
        if (!outcome.rolledBack || !outcome.rollbackVerified) {
            helper.fail("expected verified rollback, got rolledBack=" + outcome.rolledBack
                    + " rollbackVerified=" + outcome.rollbackVerified);
            return;
        }
        assertSlotsEqual(helper, expectedA, slots(ca), "chest A after read-back rollback");
        assertSlotsEqual(helper, expectedB, slots(cb), "chest B after read-back rollback");
        helper.succeed();
    }

    /**
     * E: rollback itself fails. The committer must NOT report success or a verified rollback, and the
     * original pre-image must still be available for diagnosis.
     */
    public static void commitReportsFailureWhenRollbackAlsoFails(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        List<Container> containers = containersOf(helper, a, b);
        Container ca = containers.get(0);
        Container cb = containers.get(1);

        ca.setItem(0, new ItemStack(Items.IRON_INGOT, 20));
        ca.setItem(1, new ItemStack(Items.OAK_LOG, 40));
        cb.setItem(0, new ItemStack(Items.STONE, 25));
        ca.setChanged();
        cb.setChanged();

        List<ChestSnapshot> snaps = List.of(
                ChestSnapshot.of(helper.absolutePos(a), ca, false),
                ChestSnapshot.of(helper.absolutePos(b), cb, false));
        SortPipelines.Plan plan = SortPipelines.plan(containers, snaps, true);
        if (plan.isCancelled()) {
            helper.fail("unexpected cancellation");
            return;
        }
        List<ItemStack> preImage = slots(ca);
        final int layoutSize = plan.planner.layout.size();

        // Fail on the first write, then also fail every restore attempt, so the rollback cannot
        // complete. Nothing may be reported as success or as a verified rollback.
        final boolean[] writeFailed = {false};
        final int[] restoreAttempts = {0};
        SafeCommitter.setHooks(new SafeCommitter.Hooks() {
            @Override
            public void beforeWrite(Container container, int slot, ItemStack incoming) {
                if (!writeFailed[0]) {
                    writeFailed[0] = true;
                    throw new RuntimeException("injected write failure");
                }
            }

            @Override
            public void beforeRestore(Container container, int slot) {
                restoreAttempts[0]++;
                throw new RuntimeException("injected restore failure");
            }
        });
        SafeCommitter.Prepared prepared = SafeCommitter.prepare(containers, List.of(key(helper, a), key(helper, b)));
        com.chestautosorter.server.PlannedStacks.begin();
        SafeCommitter.Outcome outcome;
        try {
            for (ChestSnapshot snap : snaps) {
                for (int i = 0; i < snap.size; i++) {
                    ItemStack s = snap.slots.get(i);
                    if (!s.isEmpty()) {
                        com.chestautosorter.server.PlannedStacks.put(com.chestautosorter.core.McStackKey.of(s), s);
                    }
                }
            }
            outcome = SafeCommitter.commit(prepared, plan.planner.layout);
        } finally {
            SafeCommitter.clearHooks();
            com.chestautosorter.server.PlannedStacks.end();
        }

        if (!writeFailed[0]) {
            helper.fail("test setup is vacuous: the write failure never fired (" + layoutSize + " layout slots)");
            return;
        }
        if (restoreAttempts[0] == 0) {
            helper.fail("test setup is vacuous: restore was never attempted");
            return;
        }
        if (outcome.success) {
            helper.fail("commit reported SUCCESS while restoration failed");
            return;
        }
        if (outcome.rollbackVerified) {
            helper.fail("commit reported a VERIFIED rollback even though restore() kept failing");
            return;
        }
        if (!outcome.rolledBack) {
            helper.fail("commit should report that a rollback was attempted");
            return;
        }
        // The pre-image must remain readable for diagnosis regardless of the outcome.
        if (preImage.isEmpty() || preImage.get(0).isEmpty()) {
            helper.fail("pre-image was lost; nothing left for recovery");
            return;
        }
        helper.succeed();
    }

    /** Preview path: planning must not write anything to any participating chest. */
    public static void previewPerformsNoWrites(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        List<Container> containers = containersOf(helper, a, b);
        Container ca = containers.get(0);
        Container cb = containers.get(1);

        ca.setItem(0, new ItemStack(Items.OAK_LOG, 30));
        ca.setItem(1, new ItemStack(Items.IRON_INGOT, 20));
        cb.setItem(0, new ItemStack(Items.STONE, 25));
        ca.setChanged();
        cb.setChanged();

        List<ItemStack> beforeA = slots(ca);
        List<ItemStack> beforeB = slots(cb);

        List<ChestSnapshot> snaps = List.of(
                ChestSnapshot.of(helper.absolutePos(a), ca, false),
                ChestSnapshot.of(helper.absolutePos(b), cb, false));

        // Any write at all would go through this hook; count them.
        final int[] writes = {0};
        SafeCommitter.setHooks(new SafeCommitter.Hooks() {
            @Override
            public void beforeWrite(Container container, int slot, ItemStack incoming) {
                writes[0]++;
            }
        });
        try {
            SortPipelines.Plan plan = SortPipelines.plan(containers, snaps, true);
            if (plan.isCancelled()) {
                helper.fail("unexpected cancellation for preview");
                return;
            }
        } finally {
            SafeCommitter.clearHooks();
        }

        if (writes[0] != 0) {
            helper.fail("preview performed " + writes[0] + " writes");
            return;
        }
        assertSlotsEqual(helper, beforeA, slots(ca), "chest A after preview");
        assertSlotsEqual(helper, beforeB, slots(cb), "chest B after preview");
        helper.succeed();
    }

    /**
     * A3: the recovery record must round-trip. Write it for a synthetic test world, read it back,
     * decode every slot and compare byte-for-byte (by full component identity and count) with the
     * snapshot it was taken from. Covers a named stack and a large count so components and big
     * numbers are exercised, not just item ids.
     */
    public static void recoveryLogRoundTrips(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        Container ca = containersOf(helper, a).get(0);

        ItemStack named = new ItemStack(Items.DIAMOND_SWORD);
        named.set(DataComponents.CUSTOM_NAME, Component.literal("Recovery Probe"));
        ca.setItem(0, named);
        ca.setItem(1, new ItemStack(Items.OAK_LOG, 40));
        ca.setItem(2, new ItemStack(Items.IRON_INGOT, 1));
        ca.setChanged();

        ChestSnapshot snap = ChestSnapshot.of(helper.absolutePos(a), ca, false);
        List<ChestSnapshot> snaps = List.of(snap);
        List<SafeCommitter.BlockPosKey> keys = List.of(key(helper, a));

        java.nio.file.Path file = com.chestautosorter.diagnostic.RecoveryLog.write(
                java.util.UUID.randomUUID(), helper.getLevel(), keys, snaps);
        if (file == null) {
            helper.fail("RecoveryLog.write returned null: the record could not be persisted");
            return;
        }
        if (!java.nio.file.Files.exists(file)) {
            helper.fail("RecoveryLog reported success but no file exists at " + file);
            return;
        }

        List<com.chestautosorter.diagnostic.RecoveryLog.RecordedSlot> readBack =
                com.chestautosorter.diagnostic.RecoveryLog.read(file);

        // Every non-empty slot of the snapshot must be present exactly once and decode identically.
        int expectedCount = 0;
        for (int i = 0; i < snap.size; i++) {
            ItemStack original = snap.slots.get(i);
            if (original.isEmpty()) {
                continue;
            }
            expectedCount++;
            boolean found = false;
            for (var rec : readBack) {
                if (rec.slot() == i) {
                    found = true;
                    if (!ItemStack.matches(original, rec.stack())) {
                        helper.fail("recovery mismatch at slot " + i + ": original=" + original
                                + " read=" + rec.stack());
                        return;
                    }
                    if (rec.stack().getCount() != original.getCount()) {
                        helper.fail("recovery count mismatch at slot " + i + ": original="
                                + original.getCount() + " read=" + rec.stack().getCount());
                        return;
                    }
                    break;
                }
            }
            if (!found) {
                helper.fail("recovery record is missing slot " + i + " (" + original + ")");
                return;
            }
        }
        if (readBack.size() != expectedCount) {
            helper.fail("recovery record has " + readBack.size() + " slots, expected " + expectedCount);
            return;
        }
        // The file must live under the recovery directory so operators can find it.
        if (!file.toString().contains("chestautosorter-recovery")) {
            helper.fail("recovery file is not in the expected directory: " + file);
            return;
        }
        helper.succeed();
    }

    /**
     * B2: measure the runtime per-slot limit actually in force (with All Stacks Infinite loaded this
     * is expected to be 512, but the value is read, never assumed), then sort a deliberately
     * oversized pile and require it to split across slots rather than be truncated. Also checks that
     * different components are never merged.
     */
    public static void runtimeStackLimitSplitsWithoutLoss(GameTestHelper helper) {
        BlockPos a = new BlockPos(1, 1, 1);
        BlockPos b = new BlockPos(3, 1, 1);
        helper.setBlock(a, Blocks.CHEST);
        helper.setBlock(b, Blocks.CHEST);
        List<Container> containers = containersOf(helper, a, b);
        Container ca = containers.get(0);
        Container cb = containers.get(1);

        // Probe the runtime limit using the real container, then build a pile just over one slot.
        ItemStack probe = new ItemStack(Items.COPPER_INGOT, 1);
        int limit = ca.getMaxStackSize(probe);
        com.chestautosorter.diagnostic.Diag.info("[B2] runtime getMaxStackSize(copper_ingot) = " + limit);

        if (limit < 1) {
            helper.fail("container reported a non-positive stack limit: " + limit);
            return;
        }
        long total = (long) limit + (limit / 4) + 1; // comfortably more than one slot, not a round number
        if (total > Integer.MAX_VALUE) {
            helper.fail("test total too large for an ItemStack count: " + total);
            return;
        }

        // Write the pile legally: an oversized total must be split across slots on the way in,
        // because a single container slot silently clamps to the runtime limit. Writing the whole
        // pile into one slot and expecting it to stick would be constructing invalid state.
        long remaining = total;
        int writeSlot = 0;
        while (remaining > 0 && writeSlot < ca.getContainerSize()) {
            int chunk = (int) Math.min(remaining, limit);
            ca.setItem(writeSlot, new ItemStack(Items.COPPER_INGOT, chunk));
            remaining -= chunk;
            writeSlot++;
        }
        if (remaining != 0) {
            helper.fail("probe chest too small to hold " + total + " at limit " + limit);
            return;
        }
        ca.setChanged();

        long written = countIdentity(List.of(ca), Items.COPPER_INGOT, true);
        if (written != total) {
            helper.fail("container accepted a legal split of " + total + " but read back " + written
                    + " (limit=" + limit + ")");
            return;
        }

        // A differently-named stack of the same item must remain a separate identity.
        ItemStack namedProbe = new ItemStack(Items.COPPER_INGOT, 1);
        namedProbe.set(DataComponents.CUSTOM_NAME, Component.literal("B2 named"));
        ca.setItem(writeSlot, namedProbe);
        ca.setChanged();

        List<ChestSnapshot> snaps = List.of(
                ChestSnapshot.of(helper.absolutePos(a), ca, false),
                ChestSnapshot.of(helper.absolutePos(b), cb, false));

        // entries() returns one entry per slot; aggregate first so the oversized pile appears as a
        // single identity, which is what the planner actually works with.
        List<com.chestautosorter.core.StackEntry> aggregated =
                com.chestautosorter.core.StackAggregator.aggregate(
                        SortPipelines.entries(snaps, containers));
        com.chestautosorter.core.StackEntry plainEntry = null;
        com.chestautosorter.core.StackEntry namedEntry = null;
        for (var e : aggregated) {
            if (e.key().itemId().equals("minecraft:copper_ingot")) {
                if (e.count() == total) {
                    plainEntry = e;
                } else if (e.count() == 1) {
                    namedEntry = e;
                }
            }
        }
        if (plainEntry == null) {
            StringBuilder sb = new StringBuilder("aggregation lost the oversized pile (" + total
                    + " copper ingots); aggregated:");
            for (var e : aggregated) {
                sb.append(' ').append(e.key().itemId()).append('x').append(e.count())
                        .append("(max=").append(e.maxStack()).append(",data=")
                        .append(e.key().dataId()).append(')');
            }
            helper.fail(sb.toString());
            return;
        }
        if (namedEntry == null) {
            helper.fail("the differently-named copper ingot was merged or lost");
            return;
        }
        if (plainEntry.maxStack() < limit) {
            helper.fail("planner saw maxStack=" + plainEntry.maxStack() + " below the runtime limit " + limit);
            return;
        }

        long beforePlain = countIdentity(containers, Items.COPPER_INGOT, true);
        long beforeNamed = countIdentity(containers, Items.COPPER_INGOT, false);

        SortPipelines.Outcome outcome = SortPipelines.runProduction(containers, snaps, true);
        if (!outcome.success) {
            helper.fail("pipeline failed at runtime limit " + limit + ": " + outcome.message);
            return;
        }

        long afterPlain = countIdentity(containers, Items.COPPER_INGOT, true);
        long afterNamed = countIdentity(containers, Items.COPPER_INGOT, false);
        if (afterPlain != beforePlain) {
            helper.fail("copper count changed: " + beforePlain + " -> " + afterPlain
                    + " (truncation or duplication)");
            return;
        }
        if (afterNamed != beforeNamed) {
            helper.fail("named copper stack changed: " + beforeNamed + " -> " + afterNamed);
            return;
        }

        // The oversized pile must now occupy more than one slot, each within the runtime limit.
        int slotsUsed = 0;
        for (Container c : containers) {
            for (int i = 0; i < c.getContainerSize(); i++) {
                ItemStack s = c.getItem(i);
                if (s.is(Items.COPPER_INGOT) && s.get(DataComponents.CUSTOM_NAME) == null) {
                    slotsUsed++;
                    if (s.getCount() > limit) {
                        helper.fail("a slot holds " + s.getCount() + " which exceeds the runtime limit " + limit);
                        return;
                    }
                }
            }
        }
        long expectedSlots = (total + limit - 1) / limit;
        if (slotsUsed < expectedSlots) {
            helper.fail("expected at least " + expectedSlots + " slots for " + total
                    + " at limit " + limit + ", found " + slotsUsed);
            return;
        }
        helper.succeed();
    }

    private static long countIdentity(List<Container> containers, net.minecraft.world.item.Item item, boolean plain) {
        long n = 0;
        for (Container c : containers) {
            for (int i = 0; i < c.getContainerSize(); i++) {
                ItemStack s = c.getItem(i);
                if (s.is(item) && (s.get(DataComponents.CUSTOM_NAME) == null) == plain) {
                    n += s.getCount();
                }
            }
        }
        return n;
    }

    private static SafeCommitter.BlockPosKey key(GameTestHelper helper, BlockPos rel) {
        BlockPos abs = helper.absolutePos(rel);
        return new SafeCommitter.BlockPosKey(abs.getX(), abs.getY(), abs.getZ());
    }

    private static List<ItemStack> slots(Container c) {
        List<ItemStack> out = new ArrayList<>(c.getContainerSize());
        for (int i = 0; i < c.getContainerSize(); i++) {
            out.add(c.getItem(i).copy());
        }
        return out;
    }

    private static void assertSlotsEqual(GameTestHelper helper, List<ItemStack> expected, List<ItemStack> actual, String what) {
        if (expected.size() != actual.size()) {
            helper.fail(what + ": size " + actual.size() + " != " + expected.size());
            return;
        }
        for (int i = 0; i < expected.size(); i++) {
            if (!ItemStack.matches(expected.get(i), actual.get(i))) {
                helper.fail(what + ": slot " + i + " expected " + expected.get(i) + " but was " + actual.get(i));
                return;
            }
        }
    }

    private static Category catOf(ItemStack s) {
        ItemClassifier clf = new ItemClassifier(ItemClassifier.defaultItemOverrides(), List.of(), ItemClassifier.defaultBuiltinRules());
        return clf.classify(id(s), new ChestSnapshot.NeoProbe(s));
    }

    private static String planDesc(com.chestautosorter.core.SortPlanner.Result plan) {
        StringBuilder sb = new StringBuilder("status=").append(plan.status).append(" {");
        for (com.chestautosorter.core.SortPlanner.SlotPlan p : plan.layout) {
            if (!p.isEmpty()) {
                sb.append("c").append(p.container).append("s").append(p.slot).append('=')
                        .append(p.entry.key().itemId()).append('x').append(p.entry.count()).append(' ');
            }
        }
        return sb.append('}').toString();
    }

    private static String dumpList(List<ItemStack> list) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < list.size(); i++) {
            if (!list.get(i).isEmpty()) {
                sb.append(i).append(':').append(id(list.get(i))).append('x').append(list.get(i).getCount()).append(' ');
            }
        }
        return sb.append(']').toString();
    }

    private static String dump(Container c) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < c.getContainerSize(); i++) {
            ItemStack s = c.getItem(i);
            if (!s.isEmpty()) {
                sb.append(i).append(':').append(id(s)).append('x').append(s.getCount()).append(' ');
            }
        }
        return sb.append(']').toString();
    }

    private static Map<String, Long> tally(List<Container> containers) {
        Map<String, Long> m = new LinkedHashMap<>();
        for (Container c : containers) {
            for (int i = 0; i < c.getContainerSize(); i++) {
                ItemStack s = c.getItem(i);
                if (!s.isEmpty()) {
                    m.merge(id(s), (long) s.getCount(), Long::sum);
                }
            }
        }
        return m;
    }

    private static String id(ItemStack s) {
        return ChestSnapshot.itemId(s);
    }

    private static boolean containerHasItem(Container c, net.minecraft.world.item.Item item) {
        for (int i = 0; i < c.getContainerSize(); i++) {
            if (c.getItem(i).is(item)) {
                return true;
            }
        }
        return false;
    }

    private static Category dominantCategory(Container c) {
        Map<Category, Long> perCat = categoriesOf(c);
        if (perCat.isEmpty()) {
            return null;
        }
        return perCat.entrySet().stream().max(Map.Entry.comparingByValue()).map(Map.Entry::getKey).orElse(null);
    }

    private static int distinctCategories(Container c) {
        return categoriesOf(c).size();
    }

    private static Map<Category, Long> categoriesOf(Container c) {
        ItemClassifier clf = new ItemClassifier(ItemClassifier.defaultItemOverrides(), List.of(), ItemClassifier.defaultBuiltinRules());
        Map<Category, Long> perCat = new LinkedHashMap<>();
        for (int i = 0; i < c.getContainerSize(); i++) {
            ItemStack s = c.getItem(i);
            if (!s.isEmpty()) {
                perCat.merge(clf.classify(id(s), new ChestSnapshot.NeoProbe(s)), (long) s.getCount(), Long::sum);
            }
        }
        return perCat;
    }

    private static long count(Container c, net.minecraft.world.item.Item item) {
        long n = 0;
        for (int i = 0; i < c.getContainerSize(); i++) {
            ItemStack s = c.getItem(i);
            if (s.is(item)) {
                n += s.getCount();
            }
        }
        return n;
    }

    static void assertEquals(GameTestHelper helper, Object expected, Object actual, String what) {
        if (!java.util.Objects.equals(expected, actual)) {
            helper.fail(what + ": expected " + expected + " but was " + actual);
        }
    }

    /**
     * Drives the real server-side validation ({@code SortService.validate}, the same method
     * {@code onRequest} calls) at the acceptance distances, and checks that range is measured from
     * the eye to the logical container bounds with a {@code <= radius} boundary.
     *
     * <p>The player stands at a fixed height and is moved along +X, so the horizontal gap to the
     * chest's block box is exactly the requested distance and eye height does not enter into it.
     */
    public static void range_rule_uses_eye_to_logical_bounds(GameTestHelper helper) {
        BlockPos chest = new BlockPos(1, 1, 1);
        helper.setBlock(chest, Blocks.CHEST);
        net.minecraft.world.entity.player.Player player = helper.makeMockServerPlayer(net.minecraft.world.level.GameType.SURVIVAL);

        int radius = 12;
        double[] inRange = {6.0, 10.0, 11.5, 12.0};
        for (double gap : inRange) {
            placeAt(player, helper, chest, gap);
            List<String> skipped = new ArrayList<>();
            var accepted = com.chestautosorter.server.SortService.validate(
                    (net.minecraft.server.level.ServerPlayer) player, List.of(helper.absolutePos(chest)), radius, skipped);
            if (accepted.isEmpty()) {
                helper.fail("gap " + gap + " should be accepted but was skipped: " + skipped);
                return;
            }
        }

        double outOfRange = 12.5;
        placeAt(player, helper, chest, outOfRange);
        List<String> skipped = new ArrayList<>();
        var accepted = com.chestautosorter.server.SortService.validate(
                (net.minecraft.server.level.ServerPlayer) player, List.of(helper.absolutePos(chest)), radius, skipped);
        if (!accepted.isEmpty()) {
            helper.fail("gap " + outOfRange + " should be rejected but was accepted");
            return;
        }
        // The server ships translation keys, not rendered text, so the assertion targets the key.
        boolean reasonIsRange = skipped.stream().anyMatch(s -> s.contains("chestautosorter.reason.too_far"));
        if (!reasonIsRange) {
            helper.fail("out-of-range rejection should carry key chestautosorter.reason.too_far, was: " + skipped);
            return;
        }
        helper.succeed();
    }

    /** Places the player {@code gap} blocks along +X from the chest, keeping a constant eye height. */
    private static void placeAt(net.minecraft.world.entity.player.Player player, GameTestHelper helper,
                                BlockPos chest, double gap) {
        BlockPos abs = helper.absolutePos(chest);
        player.setPos(abs.getX() + 0.5 + gap, abs.getY() + 0.5, abs.getZ() + 0.5);
    }
}
